### ISSUE TITLE
Prologue/epilogue optimization

### ISSUE THREAD

**Issue by mskvortsov** [access-softek/msp430-clang#16]
Input: `int foo() { return 1; }`
Clang -O2/-Os output:
```
foo:
       0:	04 12 	push	r4
       2:	04 41 	mov	r1, r4
       4:	1c 43 	mov	#1, r12
       6:	34 41 	pop	r4
       8:	30 41 	ret
```
GCC:
```
foo:
       0:	5c 43 	mov.b	#1, r12
       2:	30 41 	ret
```

**Comment by asl** [comment]
Interesting. Looks like we default to frame pointer? What does clang -fomit-frame-pointer do?

**Comment by mskvortsov** [comment]
Yep, -fomit-frame-pointer does exactly what GCC does by default.
