### ISSUE TITLE
Wrong relocation type

### ISSUE THREAD

**Issue by chbessonova** [access-softek/msp430-clang#36]
Example:
```
struct _T; 
extern const struct _T _ctype;
struct _t
{
  const char *ptr;
};
struct _t T = { &_ctype };
```
Clang produces R_MSP430_16, but R_MSP430_16_BYTE should be here.

**Comment by asl** [comment]
How does it manifest?

**Comment by chbessonova** [comment]
Both lld and msp430-elf-ld failed to link code like this with R_MSP430_16 instead of R_MSP430_16_BYTE. Found in a try to link with newlib/local.o (newlib testsuite).
