### ISSUE TITLE
Enable scmRTOS building

### ISSUE THREAD

**Issue by asl** [access-softek/msp430-clang#48]
The project is here: http://scmrtos.sourceforge.net/ScmRTOS

Seems to be dead for ~3 years, but still might be a useful test

**Comment by chbessonova** [comment]
To build with clang:
1. `git clone https://github.com/scmrtos/scmrtos-sample-projects.git --recursive`
2. Apply https://gist.github.com/chbessonova/94b2dcce0a4145eaffe20d1ec50dfd7a and https://gist.github.com/chbessonova/fd895e4bb1c0abd3f1cc864811dd12e4
3. Build 
```
PATH=~/ti/msp430-gcc/bin:~/workspace/msp430-clang/build/bin:$PATH \
make \
LIBC_INCS=/home/kbessonova/ti/msp430-gcc/msp430-elf/include \
SUPPORT_FLS=/home/kbessonova/ti/msp430-gcc/include
```
Note: `-integrated-as` turned on by default, #2 applied
