### ISSUE TITLE
LLVM generates wrong MSP430 code for indirect input constraints

### ISSUE THREAD

**Issue by asl** [access-softek/msp430-clang#75]
From https://bugs.llvm.org/show_bug.cgi?id=39993:

Since r346948, LLVM generates wrong MSP430 code for indirect input constraints inline assembly.

For example, for the following IR snippet

```
  target triple = "msp430-unknown-unknown-elf"

  define void @f() {
  entry:
    call void asm sideeffect "mov r1, $0", "*m"(i8* inttoptr (i16 256 to i8*))
    ret void
  }
```

the inline assembly is wrongly translated into
```
 	mov r1, 256(r2)
```
instead of into
```
	mov r1, &256
```

**Comment by chbessonova** [comment]
Looks like, this may fix it:
```
diff --git a/src/llvm/lib/Target/MSP430/MCTargetDesc/MSP430MCAsmInfo.cpp b/src/llvm/lib/Target/MSP430/MCTargetDesc/MSP430MCAsmInfo.cpp
index 36e9a9c3107..98bc83b41e8 100644
--- a/src/llvm/lib/Target/MSP430/MCTargetDesc/MSP430MCAsmInfo.cpp
+++ b/src/llvm/lib/Target/MSP430/MCTargetDesc/MSP430MCAsmInfo.cpp
@@ -24,4 +24,5 @@ MSP430MCAsmInfo::MSP430MCAsmInfo(const Triple &TT) {
 
   AlignmentIsInBytes = false;
   UsesELFSectionDirectiveForBSS = true;
+  UseIntegratedAssembler = true;
 }
```

**Comment by asl** [comment]
Wait, but how do we perform handling of inline assembler currently? W/o integrated assembler it should be textual, no?

**Comment by chbessonova** [comment]
Yes, MSP430AsmPrinter::printSrcMemOperand() form the string `mov r1, 256(r2)` and w/o integrated assembler we just print it. 
Maybe we should teach MSP430AsmPrinter::printSrcMemOperand behave the same way as MSP430InstPrinter::printSrcMemOperand does.

**Comment by chbessonova** [comment]
Fixed in r352178.
